version: '3.8'

services:
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - '6379:6379'
    restart: always

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - redis
      - worker
      - beat
    restart: always

  worker:
    build: .
    command: celery -A project1337 worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app
    restart: always

  beat:
    build: .
    command: celery -A project1337 beat --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app
    restart: always

  flower:
    image: mher/flower:latest
    ports:
      - '5555:5555'
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    depends_on:
      - redis
    restart: always