[tool.poetry]
name = "project1337"
version = "0.1.0"
description = ""
authors = ["Matija Pavlovic matpvl"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
