# Generated by Django 5.1.2 on 2024-10-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TargetedContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                (
                    "reply",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("status", models.CharField(default="PENDING", max_length=20)),
            ],
        ),
    ]
